# Generated by Django 3.0.3 on 2020-03-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.CharField(max_length=255)),
                ('OrderUserId', models.CharField(max_length=255)),
                ('OrderAmount', models.CharField(max_length=255)),
                ('OrderShipName', models.CharField(max_length=255)),
                ('OrderShipAddress', models.CharField(max_length=255)),
                ('OrderShipAddress2', models.CharField(max_length=255)),
                ('OrderCity', models.CharField(max_length=255)),
                ('OrderState', models.CharField(max_length=255)),
                ('OrderZip', models.CharField(max_length=255)),
                ('OrderCountry', models.CharField(max_length=255)),
                ('OrderPhone', models.CharField(max_length=255)),
                ('OrderShipping', models.CharField(max_length=255)),
                ('OrderEmail', models.CharField(max_length=255)),
                ('OrderDate', models.CharField(max_length=255)),
                ('OrderShipped', models.BooleanField(default=False)),
                ('OrderTrackingNumber', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DetailId', models.CharField(max_length=255)),
                ('DetailOrderId', models.CharField(max_length=255)),
                ('DetailProductId', models.CharField(max_length=255)),
                ('DetailName', models.CharField(max_length=255)),
                ('DetailPrice', models.CharField(max_length=255)),
                ('DetailQuantity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.TextField()),
                ('ProductPrice', models.TextField()),
                ('ProductName', models.TextField()),
                ('ProductCartDesc', models.TextField()),
                ('ProductShortDesc', models.TextField()),
                ('ProductLongDesc', models.TextField()),
                ('ProductQNA', models.TextField()),
                ('ProductThumb', models.CharField(max_length=255)),
                ('ProductImage', models.CharField(max_length=255)),
                ('ProductImage1', models.CharField(max_length=255)),
                ('ProductImage2', models.CharField(max_length=255)),
                ('ProductImage3', models.CharField(max_length=255)),
                ('ProductCategoryId', models.CharField(max_length=255)),
                ('ProductUpdateDate', models.CharField(max_length=255)),
                ('ProductStock', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.CharField(max_length=255)),
                ('categoryName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=255)),
                ('UserEmail', models.CharField(max_length=255)),
                ('UserPassword', models.CharField(max_length=255)),
                ('UserFirstName', models.CharField(max_length=255)),
                ('UserLastName', models.CharField(max_length=255)),
                ('UserCity', models.CharField(max_length=255)),
                ('UserState', models.CharField(max_length=255)),
                ('UserZip', models.CharField(max_length=255)),
                ('UserEmailVerified', models.BooleanField(default=False)),
                ('UserRegistrationCode', models.CharField(max_length=255)),
                ('UserVerificationCode', models.CharField(max_length=255)),
                ('UserPhone', models.CharField(max_length=255)),
                ('UserCountry', models.CharField(max_length=255)),
                ('UserAddress', models.CharField(max_length=255)),
                ('UserAddress2', models.CharField(max_length=255)),
            ],
        ),
    ]
