# Generated by Django 3.0.3 on 2020-04-12 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductUserReviews',
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductPrice',
            field=models.CharField(max_length=255),
        ),
    ]
