# Generated by Django 3.0.3 on 2020-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200412_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=255)),
                ('userCart', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductCategorie',
            new_name='ProductCategories',
        ),
    ]
