# Generated by Django 3.0.3 on 2020-04-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200417_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='userCart',
            new_name='cartItems',
        ),
    ]
